<?php
if(!defined('INSNOW'))
{
	die('Nice try...');
}

    echo '
  <h1><img src="', theme()->url(), '/style/images/error_log-small.png" alt="" /> ', l('Error Log'), '</h1>
  <p>', l('View a list of errors generated by PHP.'), '</p>';

    api()->context['table']->show('error_log');
?>