<?php
////////////////////////////////////////////////////////////////////////////
//                              SnowCMS v2.0                              //
//                           By the SnowCMS Team                          //
//                             www.snowcms.com                            //
//            Released under the Microsoft Reciprocal License             //
//                 www.opensource.org/licenses/ms-rl.html                 //
////////////////////////////////////////////////////////////////////////////
//                                                                        //
//       SnowCMS originally pawned by soren121 started in early 2008      //
//                                                                        //
////////////////////////////////////////////////////////////////////////////
//                                                                        //
//                  SnowCMS v2.0 began in November 2009                   //
//                                                                        //
////////////////////////////////////////////////////////////////////////////
//                       File version: SnowCMS 2.0                        //
////////////////////////////////////////////////////////////////////////////

if(!defined('INSNOW'))
{
	die('Nice try...');
}

echo '
	<div class="section-tabs">
		<ul>';

// No need to count it over and over again, right?
$length = count(api()->context['error']['options']);
for($i = 0; $i < $length; $i++)
{
	$item = api()->context['error']['options'][$i];

	echo '
		<li><a href="', $item['href'], '" title="', $item['title'], '"', ($i == 0 ? ' class="first"' : ''), (isset($item['confirm']) ? ' onclick="return confirm(\''. htmlchars($item['confirm']). '\');"' : ''), '>', $item['label'], '</a></li>';
}

echo '
		</ul>
		<div class="break">
		</div>
	</div>';

echo '
	<h3><img src="', theme()->url(), '/style/images/error_log-small.png" alt="" /> ', l('Viewing Error #%s', api()->context['error_id']), '</h3>

	<table width="100%" id="error_log_view" cellspacing="0">
		<tr>
			<th><span class="bold">', l('Date generated'), '</span></th>
			<th><span class="bold">', l('Type of error'), '</span></th>
			<th><span class="bold">', l('Generated by'), '</span></th>
		</tr>
		<tr class="tr_1">
			<td class="small">', api()->context['error']['time'], '</td>
			<td class="small">', api()->context['error']['type'], (api()->context['error']['const'] ? ' ('. api()->context['error']['const']. ')' : ''), '</td>
			<td class="small">', api()->context['error']['generated_by'], '</td>
		</tr>
		<tr>
			<th colspan="3"><span class="bold">', l('File'), '</span></th>
		</tr>
		<tr class="tr_2">
			<td style="padding: 5px;" colspan="3">', api()->context['error']['file'], (!empty(api()->context['error']['line']) ? ' <span class="bold">'. l('on line'). '</span> '. api()->context['error']['line'] : ''), '</td>
		</tr>
		<tr>
			<th colspan="3"><span class="bold">', l('URL'), '</span></th>
		</tr>
		<tr class="tr_1">
			<td style="padding: 5px;" colspan="3">', api()->context['error']['url'], '</td>
		</tr>
		<tr>
			<th colspan="3"><span class="bold">', l('Error Message'), '</span></th>
		</tr>
		<tr class="tr_2">
			<td style="padding: 5px;" colspan="3">', api()->context['error']['message'], '</td>
		</tr>
	</table>

	<p class="right"><a href="', baseurl, '/index.php?action=admin&amp;sa=error_log">', l('Back to error log'), ' &raquo;</a></p>';
?>